# Generated by Django 5.0.1 on 2024-01-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobby_name', models.CharField(max_length=30)),
                ('lobby_code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('lobby_users', models.JSONField(default=list)),
                ('lobby_host', models.JSONField(max_length=50)),
                ('lobby_host_id', models.JSONField(max_length=50)),
                ('lobby_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
